### PR TITLE
Matsl rsw hui link possible types

### PR DESCRIPTION
**Pull request by matsl**
# What

Matsl rsw hui link possible types - based on rsw branch

# Why

Basing dev work on rsw branch before potential relase. See #414 for original PR based on master.

### CODE REVIEW

**Comment by rswgnu** [comment]
Your pull request is to merge into master rather than the rsw branch.
Please fix it and then I will look at this.

Thanks,

Bob

**Comment by rswgnu** [comment]
Though you may want to wait for my next push first as it has a variable
name change affecting a bunch of files and fixes a number of other issues,
so you may want to base of that.  -- Bob

**Comment by matsl** [comment]
> Your pull request is to merge into master rather than the rsw branch.
Please fix it and then I will look at this.

Hmm... Interesting. I was not aware that you can have PRs that request to merge into a branch that is not the master branch, Will have to look into how to do that. 

When we based work on other branches at work we always did it like this. When the branch you based your work on was merged to master we rebased the PR, which was trivial. 

From the list of commits in this PR is should be clear that my commits are committed from the, at the time, latest commit in the rsw-branch so a merge with rsw should be trivial.

**Comment by matsl** [comment]
See https://github.com/rswgnu/hyperbole/pull/422 for PR merging with `rsw-branch`. Closing this.

**Pull request closed without merging**
