### PR TITLE
Add ibut:operate tests

### PR DESCRIPTION
**Pull request by matsl**
## What

First set of tests for ibut:operate

## Why 

This is new, this is tricky with many states, we need to make it stable, we need to test it! ;-)

## Note

Added some comments where I see unexpected results.

When executed interactively/manually there are additional problems with interaction what it looks like `action-key-depress-prev-point` that seems to have some strange value. By using the action key in the tests the problem went away. When running it with a fresh Emacs like using make it does not seems to matter so I have removed those hacks. (But those could be important for practical use.)

### CODE REVIEW

**Review by rswgnu — APPROVED** [review]

**Comment by matsl** [comment]
Hi @rswgnu Thanks for approving. Just want to check if you really want to merge this since many of the tests are checking what I believe is the wrong behavior. Those discrepancies are documented in comments in the test cases. What do you think of going through each discrepancy and see if they can be fixed. When that is done on master I'll removed the comments here and update the tests to reflect the proper behavior.

**Comment by rswgnu** [comment]
Yes, we can wait and I'll just work with these when I update ibut:operate
and then I can adjust to the proper behavior with the new code.  -- Bob

**Comment by matsl** [comment]
@rswgnu Updated the tests with more checks. Try to verify that the ibut is still identified as an ibut after modification. Seems it can be down to inserting proper whitespace or standard delimiter after a name is inserted.  All tests succeeds but see the comments and verification on the buffer contents that documents the misbehavior.

**Comment by matsl** [comment]
@rswgnu Marked as `WIP` while waiting for master branch to catch up.

**Comment by rswgnu** [comment]
I have updated and merged needed ibut:operate tests into master, so this PR should be abandoned.

**Pull request closed without merging**
