### PR TITLE
Add support for dired-sidebar

### PR DESCRIPTION
**Pull request by matsl**
Add support for dired-sidebar.

### CODE REVIEW

**Comment by rswgnu** [comment]
Hi Mats:

Since we already support Treemacs, is there any significant advantage of dired-sidecar over Treemacs?  I read the blurb on it and tried it briefly but want to understand any advantages first.

To finish off this PR, we should have entries for it in Changes, HYNEWS, the files that summarizes mouse and keyboard commands and an update to the Smart Key appendix in the Hyperbole Manual.

**Comment by matsl** [comment]
Different packages and different features. dired-sidebar is a more lightweight package than treemacs. It does not require you to add a folder as a project so it will open up the folder for the file your are visiting with no extra effort on your part. And it does not create any conflict with treemacs so can be used by those who prefer it etc.

**Comment by rswgnu** [comment]
Sounds good.

-- Bob

**Comment by matsl** [comment]
@rswgnu Docs updated.

**Comment by rswgnu** [comment]
Will integrate.  Thanks.  Do you think you could get C-h h to autoload hyperbole.el within the next two days or so?

-- Bob

**Comment by rswdp** [comment]
Nice job on the doc!

**Pull request merged**
