### PR TITLE
Try to use one defface for flash and highlight

### PR DESCRIPTION
**Pull request by matsl**
This is work in progress. The defface used for flash is just copy of the standard highlight and should be changed to something more suitable. But IMHO this looks like something we could use to simplify the face code.

### CODE REVIEW

**Comment by rswgnu** [comment]
Thanks, will get on it.

-- Bob

**Comment by matsl** [comment]
Hi @rswgnu Combined some work I had on the flash and color code and updated this PR. I think it works for both getting match highlighting in rolo and button flashing. Please take a look.

**Comment by rswgnu** [comment]
That's great.  Didn't know if we would get to this.  I'll take a look and
then we'll play with it.  -- Bob

**Review by rswgnu — APPROVED** [review]
That's a great reduction in code if everything works.  Have you cross-checked for any references to the symbols/names that are being deleted?  Approving assuming yes.

**Comment by matsl** [comment]
I will double check that there are no references left to the deleted function. It was some time since it initially was prepared so my memory is weak regarding what checks I did. So I will double check.

**Comment by matsl** [comment]
Double checked that there are no references left by running this:
```
grep hyrolo-initialize-highlight-face *.el
grep hproperty:background *.el
grep hproperty:foreground *.el
grep hproperty:item-highlight-color *.el
grep hproperty:but-color *.el
grep hproperty:set-flash-color *.el
grep hproperty:set-item-highlight *.el
grep hproperty:set-face-after-init *.el
```

With no output! So should be no problem with deleting those functions.

**Pull request merged**
