### PR TITLE
Allow match on different apropos formats

### PR DESCRIPTION
**Pull request by matsl**
## What

Allow match on different apropos formats

## Why

Apropos can have white space or none between command and first parentheses.

My apropos looks like this:
```
❯ apropos grep
bzegrep (1)          - search possibly bzip2 compressed files for a regular expression
bzfgrep (1)          - search possibly bzip2 compressed files for a regular expression
bzgrep (1)           - search possibly bzip2 compressed files for a regular expression
[...]
```
In is original form the test loops over the buffer until it is a match or until 5 seconds has passed. In the later case the test case fails. For each loop it tries to get more output from the process. So even if the process is slow and does not produce any output for the match the loop should ensure that it finally gets there. 

I'm not sure about how the `accept-process-output` really works but since you changed the pattern match could it not just be that your version of apropos does not have white space after the command, like this?
```
❯ apropos grep
bzegrep(1)          - search possibly bzip2 compressed files for a regular expression
bzfgrep(1)          - search possibly bzip2 compressed files for a regular expression
bzgrep(1)           - search possibly bzip2 compressed files for a regular expression
[...]
```
And what you saw was the test case just checking the wrong pattern over an over again? If you try this version does it fail on your machine?

### CODE REVIEW

**Comment by rswgnu** [comment]
Mine does not have whitespace.  I’m fine with jusy making the whitespace match optional in the regex.

-- Bob

**Comment by rswgnu** [comment]
Please make the PR against my latest version and just address this single issue.  Thanks.

**Review by rswgnu — CHANGES_REQUESTED** [review]
See prior comment.

**Comment by rswgnu** [comment]
I pushed a simple change that handles an optional space before the section number in parens.  Try it out and then abandon this pull request if good.

**Comment by rswgnu** [comment]
I changed it be ause the test was failing for me and waiting for the 5 second timeout.  The command output would not appear until some kind of other wait was done in Emacs 27.1.  This was not true of other tests.

-- Bob

**Comment by matsl** [comment]
Was it not failing because the regular expression was wrong for your apropos so you got into the timeout? With the right regexp the test case should work for both of us. I tried the timeout case, but just for emacs-29 so far, and it reports the failure fine in the *ert* output!? No strange report at al.

The construct with timeout for the failure together with `accept-process-output` was stolen from `Emacs` and the tramp test suite. It seems to be the pattern used for waiting for some output and fail on a timer if that never occurs.

Anyway, I'll mark this as `question` fro now and we can come back to it in our next talk just to sort out what happens. Your version is fine. Only problem I have with it is that it goes against the comment you gave me when you taught me about `accept-process-output`. :smile:

**Comment by rswgnu** [comment]
I tested this out and Mats version works better, so I'm approving this.

**Comment by matsl** [comment]
Thanks @rswgnu for evaluating the different versions.

**Comment by rswgnu** [comment]
Yes, let me check on it and we’ll resolve together.  Thanks.  I got most of my A-Z menu idea going today but will be awhile before I push.

-- Bob

**Pull request merged**
